#!/usr/bin/env python3
"""Build the installable, offline-capable PWA from app.html into dist/.

Usage:  python3 /home/claude/pointage/build.py

Reads app.html (a body fragment) and writes a complete document plus the
manifest, service worker, icons and .nojekyll into dist/. Stdlib + Pillow only.
Re-running overwrites dist/ with identical output when the inputs are unchanged.
"""
import hashlib
import io
import json
import math
import os
import re
import sys

from PIL import Image, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "app.html")
DIST = os.path.join(HERE, "dist")

TEAL = (11, 110, 124)  # #0B6E7C
WHITE = (255, 255, 255)
TRACK = tuple(round(t + (w - t) * 0.28) for t, w in zip(TEAL, WHITE))  # faint white on teal
SUPERSAMPLE = 4
MASKABLE_SCALE = 0.8  # content kept inside the central 80% safe zone

ICONS = [
    ("icons/apple-touch-icon.png", 180, False),
    ("icons/icon-192.png", 192, False),
    ("icons/icon-512.png", 512, False),
    ("icons/icon-512-maskable.png", 512, True),
    ("icons/favicon-32.png", 32, False),
]

HEAD = """<!doctype html><html lang="fr"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#E9EDF1" media="(prefers-color-scheme: light)">
<meta name="theme-color" content="#0E161D" media="(prefers-color-scheme: dark)">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="default">
<meta name="apple-mobile-web-app-title" content="Pointage">
<meta name="format-detection" content="telephone=no">
<link rel="manifest" href="manifest.webmanifest">
<link rel="apple-touch-icon" href="icons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="icons/favicon-32.png">
<style>/* reset that the original host provided */
:root{color-scheme:light;padding-top:env(safe-area-inset-top,0px);padding-bottom:env(safe-area-inset-bottom,0px)}
html,body{-webkit-text-size-adjust:100%}
body{margin:0;font:14px/1.4 system-ui,-apple-system,sans-serif;background:#fafafa}
img{max-width:100%}
[hidden]{display:none!important}
</style>
</head><body>
"""

TAIL = """<script>if('serviceWorker' in navigator){addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));}</script>
</body></html>
"""

MANIFEST = {
    "name": "Mon Pointage",
    "short_name": "Pointage",
    "lang": "fr",
    "start_url": "./",
    "scope": "./",
    "display": "standalone",
    "background_color": "#E9EDF1",
    "theme_color": "#0B6E7C",
    "icons": [
        {"src": "icons/icon-192.png", "sizes": "192x192", "type": "image/png", "purpose": "any"},
        {"src": "icons/icon-512.png", "sizes": "512x512", "type": "image/png", "purpose": "any"},
        {"src": "icons/icon-512-maskable.png", "sizes": "512x512", "type": "image/png", "purpose": "maskable"},
    ],
}

SW_TEMPLATE = """// Generated by build.py. The cache name changes with every build.
const VERSION = '__VERSION__';
const SHELL = 'pointage-shell-' + VERSION;
const FONTS = 'pointage-fonts-v1';
const SHELL_URLS = [
  './', './index.html', './manifest.webmanifest',
  './icons/apple-touch-icon.png', './icons/icon-192.png', './icons/icon-512.png',
  './icons/icon-512-maskable.png', './icons/favicon-32.png'
];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(SHELL).then(c => c.addAll(SHELL_URLS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== SHELL && k !== FONTS).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com') {
    e.respondWith(staleWhileRevalidate(req));
  } else if (req.mode === 'navigate') {
    e.respondWith(networkFirst(req));
  } else if (url.origin === self.location.origin) {
    e.respondWith(cacheFirst(req));
  }
});

async function cacheFirst(req) {
  const hit = await caches.match(req);
  return hit || fetch(req);
}

async function networkFirst(req) {
  const cache = await caches.open(SHELL);
  try {
    const res = await fetch(req);
    if (res.ok) cache.put('./index.html', res.clone());
    return res;
  } catch (err) {
    return (await caches.match(req, { ignoreSearch: true }))
      || (await cache.match('./index.html'))
      || new Response('Hors ligne', { status: 503, headers: { 'Content-Type': 'text/plain; charset=utf-8' } });
  }
}

async function staleWhileRevalidate(req) {
  const cache = await caches.open(FONTS);
  const cached = await cache.match(req);
  const fresh = fetch(req)
    .then(res => { if (res.ok || res.type === 'opaque') cache.put(req, res.clone()); return res; })
    .catch(() => cached || Response.error());
  return cached || fresh;
}
"""


def draw_icon(px, maskable=False):
    """Clock face with a 75% progress ring on a solid teal square."""
    n = px * SUPERSAMPLE
    k = MASKABLE_SCALE if maskable else 1.0
    img = Image.new("RGB", (n, n), TEAL)
    d = ImageDraw.Draw(img)
    c = n / 2

    def L(frac):
        """Fraction of the icon width -> supersampled pixels."""
        return frac * k * n

    def box(radius):
        return [round(c - radius), round(c - radius), round(c + radius), round(c + radius)]

    # Progress ring: faint full track, then a white arc sweeping 75% clockwise from 12 o'clock.
    ring_c, ring_w = L(0.42), max(1, round(L(0.036)))
    ring_box = box(ring_c + ring_w / 2)  # PIL strokes inward from the bbox edge
    d.ellipse(ring_box, outline=TRACK, width=ring_w)
    d.arc(ring_box, start=-90, end=180, fill=WHITE, width=ring_w)

    # Clock face outline.
    face_c, face_w = L(0.30), max(1, round(L(0.065)))
    d.ellipse(box(face_c + face_w / 2), outline=WHITE, width=face_w)

    def hand(angle_deg, length, width):
        a = math.radians(angle_deg)  # clockwise from 12 o'clock
        tx, ty = c + length * math.sin(a), c - length * math.cos(a)
        w = max(1, round(width))
        d.line([(c, c), (tx, ty)], fill=WHITE, width=w)
        r = w / 2
        d.ellipse([tx - r, ty - r, tx + r, ty + r], fill=WHITE)  # round tip

    hand(0, L(0.22), L(0.05))    # minute hand at 12
    hand(300, L(0.14), L(0.06))  # hour hand at 10

    dot = L(0.045)
    d.ellipse([c - dot, c - dot, c + dot, c + dot], fill=WHITE)

    return img.resize((px, px), Image.LANCZOS)


def png_bytes(img):
    buf = io.BytesIO()
    img.save(buf, format="PNG", optimize=True)
    return buf.getvalue()


def write(rel, data):
    path = os.path.join(DIST, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as f:
        f.write(data)


def main():
    with open(SRC, encoding="utf-8") as f:
        body = f.read()
    if re.search(r"<!doctype|<html[\s>]|<head[\s>]|<body[\s>]", body, re.IGNORECASE):
        sys.exit("app.html must be a body fragment (no doctype/html/head/body tags)")

    index_bytes = (HEAD + body + ("" if body.endswith("\n") else "\n") + TAIL).encode("utf-8")
    manifest_bytes = (json.dumps(MANIFEST, ensure_ascii=False, indent=2) + "\n").encode("utf-8")
    icon_bytes = [(rel, png_bytes(draw_icon(px, mask))) for rel, px, mask in ICONS]

    # Content hash over the page, manifest and icons: any change busts the service worker cache.
    h = hashlib.sha256(index_bytes + manifest_bytes)
    for _, data in icon_bytes:
        h.update(data)
    version = h.hexdigest()[:8]
    sw_bytes = SW_TEMPLATE.replace("__VERSION__", version).encode("utf-8")

    write("index.html", index_bytes)
    write("manifest.webmanifest", manifest_bytes)
    write("sw.js", sw_bytes)
    write(".nojekyll", b"")
    for rel, data in icon_bytes:
        write(rel, data)

    print(f"Built {DIST} (cache version {version})")


if __name__ == "__main__":
    main()
