#!/usr/bin/env python3
"""Build the installable, offline-capable PWA from app.html into dist/.

Usage:  python3 /home/claude/pointage/build.py

Reads app.html (a body fragment) and writes a complete document plus the
manifest, service worker, icons and .nojekyll into dist/. Stdlib + Pillow only.
Re-running overwrites dist/ with identical output when the inputs are unchanged.
"""
import hashlib
import io
import json
import math
import os
import re
import sys

from PIL import Image, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "app.html")
DIST = os.path.join(HERE, "dist")

TEAL = (11, 110, 124)  # #0B6E7C
WHITE = (255, 255, 255)
TRACK = tuple(round(t + (w - t) * 0.28) for t, w in zip(TEAL, WHITE))  # faint white on teal
SUPERSAMPLE = 4
MASKABLE_SCALE = 0.8  # content kept inside the central 80% safe zone

ICONS = [
    ("icons/apple-touch-icon.png", 180, False),
    ("icons/icon-192.png", 192, False),
    ("icons/icon-512.png", 512, False),
    ("icons/icon-512-maskable.png", 512, True),
    ("icons/favicon-32.png", 32, False),
]

HEAD = """<!doctype html><html lang="fr"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#FFE9F0" media="(prefers-color-scheme: light)">
<meta name="theme-color" content="#1A0B16" media="(prefers-color-scheme: dark)">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="default">
<meta name="apple-mobile-web-app-title" content="Pointage">
<meta name="format-detection" content="telephone=no">
<link rel="manifest" href="manifest.webmanifest">
<link rel="apple-touch-icon" href="icons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="icons/favicon-32.png">
<style>/* reset that the original host provided */
:root{color-scheme:light;padding-top:env(safe-area-inset-top,0px);padding-bottom:env(safe-area-inset-bottom,0px)}
html,body{-webkit-text-size-adjust:100%}
body{margin:0;font:14px/1.4 system-ui,-apple-system,sans-serif;background:#FFE9F0}
img{max-width:100%}
[hidden]{display:none!important}
</style>
</head><body>
"""

TAIL = """<script>if('serviceWorker' in navigator){addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));}</script>
</body></html>
"""

MANIFEST = {
    "name": "Mon Pointage",
    "short_name": "Pointage",
    "lang": "fr",
    "start_url": "./",
    "scope": "./",
    "display": "standalone",
    "background_color": "#FFE9F0",
    "theme_color": "#FFE9F0",
    "icons": [
        {"src": "icons/icon-192.png", "sizes": "192x192", "type": "image/png", "purpose": "any"},
        {"src": "icons/icon-512.png", "sizes": "512x512", "type": "image/png", "purpose": "any"},
        {"src": "icons/icon-512-maskable.png", "sizes": "512x512", "type": "image/png", "purpose": "maskable"},
    ],
}

SW_TEMPLATE = """// Generated by build.py. The cache name changes with every build.
const VERSION = '__VERSION__';
const SHELL = 'pointage-shell-' + VERSION;
const FONTS = 'pointage-fonts-v1';
const SHELL_URLS = [
  './', './index.html', './manifest.webmanifest',
  './icons/apple-touch-icon.png', './icons/icon-192.png', './icons/icon-512.png',
  './icons/icon-512-maskable.png', './icons/favicon-32.png'
];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(SHELL).then(c => c.addAll(SHELL_URLS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== SHELL && k !== FONTS).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.hostname === 'fonts.googleapis.com' || url.hostname === 'fonts.gstatic.com') {
    e.respondWith(staleWhileRevalidate(req));
  } else if (req.mode === 'navigate') {
    e.respondWith(networkFirst(req));
  } else if (url.origin === self.location.origin) {
    e.respondWith(cacheFirst(req));
  }
});

async function cacheFirst(req) {
  const hit = await caches.match(req);
  return hit || fetch(req);
}

async function networkFirst(req) {
  const cache = await caches.open(SHELL);
  try {
    const res = await fetch(req);
    if (res.ok) cache.put('./index.html', res.clone());
    return res;
  } catch (err) {
    return (await caches.match(req, { ignoreSearch: true }))
      || (await cache.match('./index.html'))
      || new Response('Hors ligne', { status: 503, headers: { 'Content-Type': 'text/plain; charset=utf-8' } });
  }
}

async function staleWhileRevalidate(req) {
  const cache = await caches.open(FONTS);
  const cached = await cache.match(req);
  const fresh = fetch(req)
    .then(res => { if (res.ok || res.type === 'opaque') cache.put(req, res.clone()); return res; })
    .catch(() => cached || Response.error());
  return cached || fresh;
}
"""


def draw_icon(px, maskable=False):
    """Liquid-glass icon: pink gradient, glass disc, white clock and progress arc."""
    n = px * SUPERSAMPLE
    k = MASKABLE_SCALE if maskable else 1.0
    top, bot = (255, 193, 214), (232, 51, 111)
    grad = Image.new("RGB", (1, n))
    grad.putdata([tuple(round(t + (u - t) * y / (n - 1)) for t, u in zip(top, bot)) for y in range(n)])
    img = grad.resize((n, n)).convert("RGBA")
    c = n / 2

    def layer():
        return Image.new("RGBA", (n, n), (0, 0, 0, 0))

    def L(frac):
        return frac * k * n

    # soft white bloom, top-left
    bloom = Image.new("L", (n, n), 0)
    bd = ImageDraw.Draw(bloom)
    bx, by, br = n * 0.22, n * 0.18, n * 0.55
    steps = 60
    for i in range(steps):
        r = br * (1 - i / steps)
        bd.ellipse([bx - r, by - r, bx + r, by + r], fill=round(110 * (i + 1) / steps / 1.0 * 0.55))
    img = Image.alpha_composite(img, Image.merge("RGBA", (Image.new("L", (n, n), 255),) * 3 + (bloom,)))

    # glass disc + rim
    disc = layer(); dd = ImageDraw.Draw(disc)
    R = L(0.40)
    dd.ellipse([c - R, c - R, c + R, c + R], fill=(255, 255, 255, 71))
    rim_w = max(1, round(0.012 * px * SUPERSAMPLE * k))
    dd.ellipse([c - R, c - R, c + R, c + R], outline=(255, 255, 255, 153), width=rim_w)
    img = Image.alpha_composite(img, disc)

    d = ImageDraw.Draw(img)
    # progress arc ~70%
    ar = L(0.33); aw = max(1, round(L(0.036)))
    ab = [round(c - ar), round(c - ar), round(c + ar), round(c + ar)]
    d.arc(ab, start=-90, end=-90 + 252, fill=(255, 255, 255, 255), width=aw)
    for ang in (-90, -90 + 252):
        a = math.radians(ang)
        ex, ey = c + (ar - aw / 2) * math.cos(a), c + (ar - aw / 2) * math.sin(a)
        d.ellipse([ex - aw / 2, ey - aw / 2, ex + aw / 2, ey + aw / 2], fill=(255, 255, 255, 255))

    def hand(angle_deg, length, width):
        a = math.radians(angle_deg)
        tx, ty = c + length * math.sin(a), c - length * math.cos(a)
        w = max(1, round(width))
        d.line([(c, c), (tx, ty)], fill=WHITE, width=w)
        r = w / 2
        d.ellipse([tx - r, ty - r, tx + r, ty + r], fill=WHITE)
        d.ellipse([c - r, c - r, c + r, c + r], fill=WHITE)

    hand(0, L(0.21), L(0.05))
    hand(120, L(0.14), L(0.06))
    dot = L(0.04)
    d.ellipse([c - dot, c - dot, c + dot, c + dot], fill=WHITE)

    # top-half sheen, clipped to the disc and faded downward
    sh = Image.new("L", (n, n), 0)
    sd = ImageDraw.Draw(sh)
    sd.ellipse([c - R * 0.92, c - R * 0.98, c + R * 0.92, c + R * 0.05], fill=56)
    fade = Image.linear_gradient("L").resize((n, n))  # black top -> white bottom
    fade = fade.point(lambda v: 255 - v)
    sh = Image.composite(sh, Image.new("L", (n, n), 0), fade)
    white = Image.new("RGBA", (n, n), (255, 255, 255, 255))
    white.putalpha(sh)
    img = Image.alpha_composite(img, white)

    return img.convert("RGB").resize((px, px), Image.LANCZOS)


def png_bytes(img):
    buf = io.BytesIO()
    img.save(buf, format="PNG", optimize=True)
    return buf.getvalue()


def write(rel, data):
    path = os.path.join(DIST, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as f:
        f.write(data)


def main():
    with open(SRC, encoding="utf-8") as f:
        body = f.read()
    if re.search(r"<!doctype|<html[\s>]|<head[\s>]|<body[\s>]", body, re.IGNORECASE):
        sys.exit("app.html must be a body fragment (no doctype/html/head/body tags)")

    index_bytes = (HEAD + body + ("" if body.endswith("\n") else "\n") + TAIL).encode("utf-8")
    manifest_bytes = (json.dumps(MANIFEST, ensure_ascii=False, indent=2) + "\n").encode("utf-8")
    icon_bytes = [(rel, png_bytes(draw_icon(px, mask))) for rel, px, mask in ICONS]

    # Content hash over the page, manifest and icons: any change busts the service worker cache.
    h = hashlib.sha256(index_bytes + manifest_bytes)
    for _, data in icon_bytes:
        h.update(data)
    version = h.hexdigest()[:8]
    sw_bytes = SW_TEMPLATE.replace("__VERSION__", version).encode("utf-8")

    write("index.html", index_bytes)
    write("manifest.webmanifest", manifest_bytes)
    write("sw.js", sw_bytes)
    write(".nojekyll", b"")
    for rel, data in icon_bytes:
        write(rel, data)

    print(f"Built {DIST} (cache version {version})")


if __name__ == "__main__":
    main()
